import { useState, useEffect, FormEvent } from 'react';
import { 
  Check, CheckCircle2, MapPin, Navigation, Sparkles, MessageSquare, 
  Send, ShieldCheck, Clock, UserCheck, Star, Trash2 
} from 'lucide-react';
import { BookingDetails } from '../types';
import { TOP_MAIDS } from '../data/mockData';

interface BookingTrackerProps {
  booking: BookingDetails;
  onCancelBooking: () => void;
}

interface Message {
  sender: 'user' | 'maid';
  text: string;
  time: string;
}

export default function BookingTracker({ booking, onCancelBooking }: BookingTrackerProps) {
  // Simulator progression states
  const [currentStatus, setCurrentStatus] = useState<'pending' | 'confirmed' | 'cleaning' | 'completed'>(booking.status);
  
  // Simulated Chat state
  const [chatInput, setChatInput] = useState('');
  const [chatHistory, setChatHistory] = useState<Message[]>([
    { sender: 'maid', text: 'Hi! I am confirmed for your clean! Let me know if there are any gate codes or parking constraints.', time: 'Just now' }
  ]);

  // Sync state if booking updates externally
  useEffect(() => {
    setCurrentStatus(booking.status);
  }, [booking]);

  const assignedMaid = TOP_MAIDS.find(m => m.id === booking.assignedMaidId) || TOP_MAIDS[0];

  // Progression steps info
  const stepConfig = [
    { id: 'pending', label: 'Order Registered', desc: 'Secure quote locked in & reviewer matched' },
    { id: 'confirmed', label: 'Maid Dispatched', desc: 'Specialist is en-route to location' },
    { id: 'cleaning', label: 'Active Cleaning', desc: 'Detailed scrubbing of your spaces' },
    { id: 'completed', label: 'Pristine Inspection', desc: '100% finished custom walk-through' }
  ];

  const currentStepIndex = stepConfig.findIndex(item => item.id === currentStatus);

  // Hardcoded cleaning chores listing mapped to stages
  const choreChecklist = [
    { task: 'Dust all accessible tables & baseboards', stage: 1 },
    { task: 'Empty wastebaskets & sanitize receptacles', stage: 1 },
    { task: 'Vacuum carpet rugs & polish hardwood', stage: 2 },
    { task: 'Sanitize toilet bowl, shower glass & faucets', stage: 2 },
    { task: 'Meticulous linen replacement & bed making', stage: 3 },
    { task: 'Specialist organic air deodorizer spray', stage: 3 }
  ];

  const handleSendMessage = (e: FormEvent) => {
    e.preventDefault();
    if (!chatInput.trim()) return;
    
    const userMsg: Message = { sender: 'user', text: chatInput, time: 'Just now' };
    const updatedHistory = [...chatHistory, userMsg];
    setChatHistory(updatedHistory);
    setChatInput('');

    // Simulated autogenerated response from maid
    setTimeout(() => {
      let maidReply = "Sounds great! Appreciate the heads-up. See you soon!";
      const promptLower = chatInput.toLowerCase();
      if (promptLower.includes('key') || promptLower.includes('under') || promptLower.includes('door') || promptLower.includes('lock')) {
        maidReply = `Got it! I will locate the entry spot safely and let myself in. Thank you!`;
      } else if (promptLower.includes('dog') || promptLower.includes('cat') || promptLower.includes('pet')) {
        maidReply = `Aw, wonderful! I absolutely love pets! I will be very careful around them and use our standard pet-safe eco solutions.`;
      } else if (promptLower.includes('park') || promptLower.includes('space')) {
        maidReply = `Perfect, thank you for the parking directions! It helps a lot.`;
      } else if (promptLower.includes('cancel') || promptLower.includes('reschedule')) {
        maidReply = `Oh, I understand. If you need any adjustments, please let our customer service hotline know!`;
      }
      
      setChatHistory(prev => [...prev, { sender: 'maid', text: maidReply, time: 'Just now' }]);
    }, 1500);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8" id="booking-tracker-stage">
      
      {/* Simulation Helper Panel */}
      <div className="bg-gray-900 text-white rounded-3xl p-5 mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4 shadow-xl border-4 border-brand-violet/20" id="sandbox-admin-bar">
        <div className="flex items-center gap-3">
          <div className="bg-brand-pink/20 text-brand-pink p-2 rounded-xl">
            <Sparkles className="w-5 h-5 animate-spin-slow" />
          </div>
          <div>
            <h4 className="font-bold text-sm tracking-wide text-white uppercase">🔬 Service Simulator Panel</h4>
            <p className="text-xs text-gray-400">Click below to transition status states and test real-time checklist changes!</p>
          </div>
        </div>
        <div className="flex flex-wrap gap-2">
          {stepConfig.map((st) => (
            <button
              key={st.id}
              onClick={() => setCurrentStatus(st.id as any)}
              className={`px-3 py-1.5 rounded-lg text-xs font-black uppercase tracking-wider transition-all select-none ${
                currentStatus === st.id
                  ? 'bg-gradient-to-r from-brand-violet to-brand-pink text-white shadow-md'
                  : 'bg-gray-800 text-gray-400 hover:bg-gray-700 hover:text-white'
              }`}
            >
              {st.label.split(' ')[0]}
            </button>
          ))}
        </div>
      </div>

      <div className="text-center max-w-xl mx-auto mb-10">
        <span className="px-3.5 py-1.5 bg-brand-violet-light text-brand-violet rounded-full text-xs font-black uppercase tracking-widest inline-block border border-brand-violet/10">
          Tracking Code: {booking.id}
        </span>
        <h2 className="font-display text-2xl sm:text-4xl font-extrabold text-gray-900 mt-2.5">
          Your Home is Next in Line!
        </h2>
        <p className="text-xs sm:text-sm text-gray-400 mt-1.5">
          Order issued at {new Date(booking.createdAt).toLocaleDateString()} {new Date(booking.createdAt).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Left Column (8 units) - Timeline Progress Tracker */}
        <div className="lg:col-span-8 space-y-6">
          <div className="bg-white rounded-3xl p-6 sm:p-8 border border-gray-100 shadow-xl" id="milestones-card">
            <h3 className="font-display text-lg sm:text-xl font-extrabold text-gray-900 mb-8 flex items-center gap-2">
              <Clock className="w-5 h-5 text-brand-violet" />
              Service Checklist Progress
            </h3>

            {/* Stepper Timeline UI */}
            <div className="relative pl-6 border-l-2 border-gray-100 ml-3 space-y-8" id="visual-timeline-stepper">
              {stepConfig.map((step, idx) => {
                const isActive = idx === currentStepIndex;
                const isCompleted = idx < currentStepIndex;
                const isUpcoming = idx > currentStepIndex;

                return (
                  <div key={step.id} className="relative" id={`timeline-step-${step.id}`}>
                    {/* Stepper Node Indicator */}
                    <div className={`absolute -left-10 top-0.5 w-8 h-8 rounded-full flex items-center justify-center transition-all border ${
                      isActive 
                        ? 'bg-gradient-to-tr from-brand-violet to-brand-pink border-white text-white scale-110 ring-4 ring-brand-violet/15'
                        : isCompleted 
                        ? 'bg-green-500 border-white text-white' 
                        : 'bg-white border-gray-200 text-gray-400'
                    }`}>
                      {isCompleted ? (
                        <Check className="w-4 h-4" />
                      ) : (
                        <span className="text-xs font-extrabold">{idx + 1}</span>
                      )}
                    </div>

                    {/* Step description */}
                    <div>
                      <h4 className={`font-display text-base font-extrabold ${
                        isActive ? 'text-brand-violet' : isCompleted ? 'text-gray-800' : 'text-gray-400'
                      }`}>
                        {step.label}
                      </h4>
                      <p className={`text-xs sm:text-sm mt-0.5 ${isActive ? 'text-gray-600 font-medium' : 'text-gray-400'}`}>
                        {step.desc}
                      </p>
                    </div>

                    {/* Show a mini checklist inside the ACTIVE stage */}
                    {isActive && (
                      <div className="bg-gray-50/50 border border-gray-100 rounded-2xl p-4.5 mt-4 space-y-3 animate-fadeIn" id="progress-chore-sublist">
                        <span className="text-[10px] font-black tracking-widest uppercase text-brand-pink block mb-1">
                          Current Action Requirements
                        </span>
                        {choreChecklist.map((chore, cidx) => {
                          const isFinished = currentStepIndex > chore.stage;
                          return (
                            <div key={cidx} className="flex items-start gap-2.5 text-xs">
                              <div className={`mt-0.5 w-4 h-4 rounded-full flex items-center justify-center ${
                                isFinished ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-300'
                              }`}>
                                <CheckCircle2 className="w-3.5 h-3.5" />
                              </div>
                              <span className={`font-semibold ${isFinished ? 'text-gray-400 line-through' : 'text-gray-700'}`}>
                                {chore.task}
                              </span>
                            </div>
                          );
                        })}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Simulated Tracking Map Vector UI */}
          <div className="bg-white rounded-3xl p-6 border border-gray-100 shadow-xl overflow-hidden" id="interactive-map-card">
            <h3 className="font-display text-lg sm:text-xl font-extrabold text-gray-900 mb-4 flex items-center gap-2">
              <Navigation className="w-5 h-5 text-brand-violet" />
              <span>Cleaner Tracker MAP</span>
              <span className="text-[10px] uppercase tracking-wider bg-green-50 text-green-700 border border-green-100 px-2 py-0.5 rounded-full font-bold">LIVE GPS ACTIVATED</span>
            </h3>
            
            {/* Interactive map visualization canvas drawing */}
            <div className="relative bg-violet-50/40 border border-brand-violet/5 rounded-2xl h-56 flex items-center justify-center overflow-hidden" id="gps-vector-viewport">
              
              {/* Map grid decoration line paths */}
              <div className="absolute inset-0 opacity-15 pointer-events-none" style={{ backgroundImage: 'radial-gradient(circle, #7c3aed 1px, transparent 1px)', backgroundSize: '16px 16px' }} />
              
              {/* Vector Street Lines */}
              <svg className="absolute inset-0 w-full h-full opacity-20" xmlns="http://www.w3.org/2000/svg">
                <line x1="10%" y1="0%" x2="10%" y2="100%" stroke="#7c3aed" strokeWidth="4" />
                <line x1="50%" y1="0%" x2="50%" y2="100%" stroke="#7c3aed" strokeWidth="4" />
                <line x1="90%" y1="0%" x2="90%" y2="100%" stroke="#7c3aed" strokeWidth="4" />
                <line x1="0%" y1="30%" x2="100%" y2="30%" stroke="#7c3aed" strokeWidth="4" />
                <line x1="0%" y1="70%" x2="100%" y2="70%" stroke="#7c3aed" strokeWidth="4" />
              </svg>

              {/* Home Marker Node */}
              <div className="absolute left-[70%] top-[40%] text-center flex flex-col items-center">
                <div className="bg-brand-pink text-white p-2.5 rounded-2xl shadow-lg ring-4 ring-brand-pink/20 animate-pulse">
                  <MapPin className="w-5 h-5" />
                </div>
                <span className="text-[10px] font-black tracking-wide text-gray-700 bg-white shadow-sm px-2 py-0.5 mt-2 rounded-md">
                  HOME
                </span>
              </div>

              {/* Dispatched Car Marker Node */}
              <div 
                className={`absolute text-center flex flex-col items-center transition-all duration-1000 ${
                  currentStatus === 'pending' ? 'left-[10%] top-[30%]' :
                  currentStatus === 'confirmed' ? 'left-[40%] top-[50%] animate-bounce' :
                  'left-[70%] top-[40%]'
                }`}
                id="gps-cleaner-capsule"
              >
                <div className="bg-brand-violet text-white p-2.5 rounded-full shadow-lg ring-4 ring-brand-violet/20">
                  <span className="text-lg select-none">🚗</span>
                </div>
                <span className="text-[10px] font-bold text-white bg-brand-violet shadow-sm px-2 py-0.5 mt-2 rounded-md">
                  {assignedMaid.name.split(' ')[0]} {currentStatus === 'cleaning' ? '(Arrived!)' : '(Moving)'}
                </span>
              </div>

              {/* Compass / Speed Display */}
              <div className="absolute bottom-3 left-3 bg-white/90 backdrop-blur border border-gray-100 rounded-xl p-2.5 flex items-center gap-2">
                <div className="bg-gray-100 text-gray-700 p-1.5 rounded-lg text-xs font-black">
                  GPS
                </div>
                <div>
                  <span className="block text-[8px] uppercase tracking-wider text-gray-400 font-bold">Speed</span>
                  <span className="block text-xs font-black text-gray-800">
                    {currentStatus === 'pending' ? '0 MPH (Standby)' : currentStatus === 'confirmed' ? '28 MPH' : '0 MPH (Parked)'}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column (4 units) - Maid Profile & Active Messaging */}
        <div className="lg:col-span-4 space-y-6">
          
          {/* Maid Bio card */}
          <div className="bg-white rounded-3xl p-6 border border-gray-100 shadow-xl" id="maid-expert-card">
            <h4 className="text-xs font-black tracking-widest text-brand-pink uppercase mb-4">Assigned Cleaning Professional</h4>
            
            <div className="flex items-center gap-4 border-b border-gray-50 pb-5 mb-5">
              <img 
                src={assignedMaid.avatar} 
                alt={assignedMaid.name} 
                className="w-16 h-16 rounded-2xl object-cover shadow-md border-2 border-brand-violet-light"
                referrerPolicy="no-referrer"
              />
              <div>
                <h4 className="font-display font-extrabold text-gray-900 text-base flex items-center gap-1.5">
                  {assignedMaid.name}
                  <UserCheck className="w-4 h-4 text-brand-violet" />
                </h4>
                <p className="text-xs font-bold text-brand-violet mt-0.5">{assignedMaid.specialty}</p>
                <div className="flex items-center gap-1 mt-1.5" id="maid-review-rating">
                  <Star className="w-3.5 h-3.5 fill-amber-400 stroke-amber-400" />
                  <span className="text-xs font-black text-gray-800">{assignedMaid.rating}</span>
                  <span className="text-[10px] text-gray-400">({assignedMaid.completedJobs} jobs done)</span>
                </div>
              </div>
            </div>

            <p className="text-xs leading-relaxed text-gray-500 italic bg-gray-50 rounded-xl p-4 border border-gray-100">
              "{assignedMaid.bio}"
            </p>
          </div>

          {/* Active instant message system with maid */}
          <div className="bg-white border border-gray-100 rounded-3xl overflow-hidden shadow-xl" id="cleaner-messages-shell">
            <div className="bg-gradient-to-r from-brand-violet to-brand-pink px-5 py-4.5 text-white flex items-center gap-3">
              <div className="relative">
                <img 
                  src={assignedMaid.avatar} 
                  alt={assignedMaid.name} 
                  className="w-9 h-9 rounded-full object-cover border border-white"
                  referrerPolicy="no-referrer"
                />
                <span className="absolute bottom-0 right-0 w-2.5 h-2.5 bg-green-500 border border-white rounded-full" />
              </div>
              <div>
                <h4 className="font-bold text-sm leading-tight">{assignedMaid.name}</h4>
                <p className="text-[9px] uppercase tracking-wider text-pink-100 font-bold">Online Dispatch Chat</p>
              </div>
            </div>

            {/* Chat list viewport */}
            <div className="h-56 p-4 overflow-y-auto space-y-3 bg-gray-50/50" id="chat-messages-container">
              {chatHistory.map((msg, index) => {
                const isMaid = msg.sender === 'maid';
                return (
                  <div key={index} className={`flex ${isMaid ? 'justify-start' : 'justify-end'}`}>
                    <div className={`max-w-[80%] rounded-2xl px-3.5 py-2.5 text-xs shadow-sm ${
                      isMaid 
                        ? 'bg-white border border-gray-100 text-gray-800 rounded-tl-none' 
                        : 'bg-brand-violet text-white rounded-tr-none'
                    }`}>
                      <p>{msg.text}</p>
                      <span className={`block text-[8px] mt-1 text-right  ${isMaid ? 'text-gray-400' : 'text-violet-200'}`}>
                        {msg.time}
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Input send bar footer */}
            <form onSubmit={handleSendMessage} className="p-3 bg-white border-t border-gray-100 flex gap-2" id="chat-input-bar">
              <input
                type="text"
                placeholder="Ask your maid something..."
                value={chatInput}
                onChange={(e) => setChatInput(e.target.value)}
                className="w-full text-xs font-semibold px-4 py-2.5 bg-gray-50 rounded-xl focus:outline-none focus:ring-1 focus:ring-brand-violet text-gray-800"
              />
              <button
                type="submit"
                className="bg-brand-violet hover:bg-brand-violet-dark text-white p-2.5 rounded-xl transition-all"
              >
                <Send className="w-4 h-4" />
              </button>
            </form>
          </div>

          {/* Cancellation controls */}
          <div className="flex flex-col gap-3.5">
            <div className="p-5 border border-amber-200 bg-amber-50 rounded-2xl" id="cancellation-policy-bullet">
              <h5 className="font-bold text-amber-800 text-xs flex items-center gap-1">
                🛡️ Flex-Reschedule Active
              </h5>
              <p className="text-[10px] text-amber-700 leading-normal mt-1">
                Need to change the date or key location? Rescheduling is 100% free with Sevzy up to 2 hours before the scheduled time slot slot.
              </p>
            </div>
            
            <button
              id="cancel-booking-button"
              onClick={onCancelBooking}
              className="w-full border border-gray-200 hover:border-red-200 bg-white text-gray-500 hover:text-red-600 text-xs font-bold py-3.5 rounded-2xl flex items-center justify-center gap-2 transition-all"
            >
              <Trash2 className="w-4 h-4" />
              <span>Cancel / Rematch Booking</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
